# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

kstest_c <- function(x, y) {
    .Call('flowIncubator_kstest_c', PACKAGE = 'flowIncubator', x, y)
}

